slnVELogisticCloud/VELogisticCloud.App.Web/Models/Seguridad/PerfilViewModel.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace VELogisticCloud.App.Web.Models.Seguridad
{
    public class PerfilViewModel
    {
        [Key]
        public int IdPerfil { get; set; }

        [Required(ErrorMessage = "El campo {0} es obligatorio.")]
        public string Nombre { get; set; }

        [Required(ErrorMessage = "El campo {0} es obligatorio.")]
        public string Descripcion { get; set; }

        public int IdEstado { get; set; }

        public int IdUsuarioRegistro { get; set; }

        public DateTime FechaRegistro { get; set; }

        public int IdUsuarioActualiza { get; set; }

        public string FechaActualizacion { get; set; }
    }
}

slnVELogisticCloud/VELogisticCloud.App.Web/Models/Seguridad/UsuarioRegistroViewModel.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
//using VELogisticCloud.CrossCutting.Entidad.Seguridad;

namespace VELogisticCloud.App.Web.Models.Seguridad
{
    public class UsuarioRegistroViewModel
    {
        [Required]        
        [Display(Name = "Login")]
        public string Login { get; set; }

        [Required]
        [EmailAddress]
        [Display(Name = "Email")]
        public string Email { get; set; }

        [Required]
        [StringLength(20, ErrorMessage = "El {0} debe tener al menos {2} y un maximo de {1} characters.", MinimumLength = 6)]
        [DataType(DataType.Password)]
        [Display(Name = "Password")]
        public string Password { get; set; }

        [DataType(DataType.Password)]
        [Display(Name = "Confirmar password")]
        [Compare("Password", ErrorMessage = "El password y la confirmacion del password no coinciden.")]
        public string ConfirmPassword { get; set; }

        [Required(ErrorMessage = "El campo {0} es obligatorio.")]
        public string Apellidos { get; set; }

        [Required(ErrorMessage = "El campo {0} es obligatorio.")]
        public string Nombres { get; set; }

        public string TelefonoMovil { get; set; }

        [Required(ErrorMessage = "Seleccione un Estado valido.")]        
        public int IdEstado { get; set; }

        //public List<Estado> Estados { get; set; }

        public string FechaRegistro { get; set; }
    }
}

slnVELogisticCloud/VELogisticCloud.App.Web/Models/Seguridad/UsuarioViewModel.cs
using System.Collections.Generic;
//using VELogisticCloud.CrossCutting.Entidad.Seguridad;

namespace VELogisticCloud.App.Web.Models.Seguridad
{
    public class UsuarioViewModel
    {
        //public Usuario Entidad { get; set; }
        //public List<Estado> Estados { get; set; }
    }
}

slnVELogisticCloud/VELogisticCloud.App.Web/Controllers/Seguridad/OpcionController.cs
using Microsoft.AspNetCore.Mvc;

namespace VELogisticCloud.App.Web.Controllers.Seguridad
{
    public class OpcionController : Controller
    {
        [HttpGet]
        public IActionResult Index()
        {
            return View("~/Views/Seguridad/Opcion/Index.cshtml");
        }

        [HttpGet]
        public IActionResult Registrar()
        {
            return View("~/Views/Seguridad/Opcion/Registro.cshtml");
        }

        [HttpGet]
        public IActionResult Editar()
        {
            return View("~/Views/Seguridad/Opcion/Registro.cshtml");
        }

    }
}

slnVELogisticCloud/VELogisticCloud.App.Web/Controllers/Seguridad/PerfilController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using VELogisticCloud.Models;
using VELogisticCloud.Servicio.Data.Repository;

namespace VELogisticCloud.App.Web.Controllers.Seguridad
{
    public class PerfilController : Controller
    {
        private readonly IContenedorTrabajo _contenedorTrabajo;

        public PerfilController(IContenedorTrabajo contenedorTrabajo)
        {
            _contenedorTrabajo = contenedorTrabajo;
        }

        public IActionResult Index()
        {
            return View("~/Views/Seguridad/Perfil/Index.cshtml");
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View("~/Views/Seguridad/Perfil/Create.cshtml");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Perfil entidad)
        {
            if (ModelState.IsValid)
            {
                entidad.IdUsuarioRegistro = 1;
                entidad.FechaRegistro = DateTime.Now;

                //entidad.IdUsuarioActualiza = 1;
                //entidad.FechaActualizacion = DateTime.Now;

                _contenedorTrabajo.Perfil.Add(entidad);
                _contenedorTrabajo.Save();
                return RedirectToAction(nameof(Index));
            }
            return View("~/Views/Seguridad/Perfil/Create.cshtml",entidad);
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            Perfil entidad = _contenedorTrabajo.Perfil.Get(id);
            if (entidad == null)
            {
                return NotFound();
            }

            return View("~/Views/Seguridad/Perfil/Edit.cshtml",entidad);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Perfil entidad)
        {
            if (ModelState.IsValid)
            {
                _contenedorTrabajo.Perfil.Update(entidad);
                _contenedorTrabajo.Save();
                return RedirectToAction(nameof(Index));
            }
            return View("~/Views/Seguridad/Perfil/Edit.cshtml",entidad);
        }


        #region llamadas API

        [HttpGet]
        public IActionResult GetAll()
        {
            return Json(new { data = _contenedorTrabajo.Perfil.GetAll() });
        }

        [HttpDelete]
        public IActionResult Delete(int id)
        {
            var objFromDb = _contenedorTrabajo.Perfil.Get(id);
            if (objFromDb == null)
            {
                return Json(new { success = false, message = "Error eliminando perfil" });
            }

            _contenedorTrabajo.Perfil.Remove(objFromDb);
            _contenedorTrabajo.Save();
            return Json(new { success = true, message = "Puerto borrado satisfactoriamente." });
        }

        #endregion
    }
}

slnVELogisticCloud/VELogisticCloud.App.Web/Controllers/Seguridad/RolController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using VELogisticCloud.Models.Security;

namespace VELogisticCloud.App.Web.Controllers.Seguridad
{
    public class RolController : Controller
    {
        private readonly RoleManager<IdentityRole> _roleManager;

        public RolController(RoleManager<IdentityRole> roleManager)
        {
            _roleManager = roleManager;
        }

        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View("~/Views/Seguridad/Perfil/Create.cshtml");
        }

        [HttpPost]
        public async Task<IActionResult> Create(RolViewModel model)
        {

            IdentityRole identityRole = new IdentityRole()
            {
                Name = model.Nombre
            };

            var result = await _roleManager.CreateAsync(identityRole);

            return View("~/Views/Seguridad/Perfil/Create.cshtml", model);
        }
    }
}

slnVELogisticCloud/VELogisticCloud.App.Web/Controllers/Seguridad/UsuarioController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using VELogisticCloud.CrossCutting.Comun;
using VELogisticCloud.CrossCutting.DTO;
using VELogisticCloud.Model.Identity;
using VELogisticCloud.Models.ViewModel;
using VELogisticCloud.Servicio.Data;
using VELogisticCloud.Servicio.Data.Repository;

namespace VELogisticCloud.App.Web.Controllers.Seguridad
{
    [Authorize(Roles = Rol.ADMINISTRADOR)]
    public class UsuarioController : Controller
    {
        private readonly IContenedorTrabajo _contenedorTrabajo;

        public UsuarioController(IContenedorTrabajo contenedorTrabajo)
        {
            _contenedorTrabajo = contenedorTrabajo;
        }

        [HttpGet]
        public IActionResult Index()
        {
            UsuarioViewModel model = new UsuarioViewModel();

            model.Estados = new EstadoRepository().GetListaEstado().ToList();

            return View("~/Views/Seguridad/Usuario/Index.cshtml", model);
        }

        [HttpPost]
        //[Authorize]
        public async Task<IActionResult> ListarUsuario(UsuarioDTO usuario)
        {

            EntidadConsultada<UsuarioDTO> response = new EntidadConsultada<UsuarioDTO>();

            var draw = HttpContext.Request.Form["draw"].FirstOrDefault();
            var start = Request.Form["start"].FirstOrDefault();
            var length = Request.Form["length"].FirstOrDefault();

            response = await _contenedorTrabajo.Usuario.ListarUsuarios(usuario,
                                                        start != null ? Convert.ToInt32(start) : 0,
                                                        length != null ? Convert.ToInt32(length) : 0);
            response.Lista.ForEach(a => a.NombreEstado = "Activo");

            //foreach (var item in response.Lista)
            //{
            //    if (item.Email == "admin@mail.com")
            //        item.NombreRol = "Administrador";
            //    else if (item.Email == "customer@mail.com")
            //        item.NombreRol = "Customer Service";
            //    else
            //        item.NombreRol = "Usuario";
            //}

            return Json(new
            {
                draw,
                recordsFiltered = response.Lista.Count(),
                recordsTotal = response.TotalRegistros,
                data = response.Lista
            });
        }
    }
}

slnVELogisticCloud/VELogisticCloud.App.Web/Views/Seguridad/Opcion/Index.cshtml
@{
    Layout = "_Layout";
}
<!-- Content Header (Page header) -->
<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Opci&oacute;n</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a asp-controller="Home" asp-action="Index">Inicio</a></li>
                    <li class="breadcrumb-item">Administraci&oacute;n</li>
                    <li class="breadcrumb-item">Seguridad</li>
                    <li class="breadcrumb-item"><a asp-controller="Opcion" asp-action="Index">Opci&oacute;n</a></li>
                    <li class="breadcrumb-item active">Consultar</li>
                </ol>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>


<!-- Main content -->
<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card card-outline card-primary">
                    <div class="card-header">
                        <h3 class="card-title">Filtros de Consulta</h3>
                        <div class="card-tools">
                            <button type="button" class="btn btn-tool" data-card-widget="collapse">
                                <i class="fas fa-minus"></i>
                            </button>
                        </div>
                        <!-- /.card-tools -->
                    </div>
                    <!-- /.card-header -->
                    <div class="card-body">

                        <form role="form">
                            <div class="row">
                                <div class="col-sm-4">
                                    <!-- text input -->
                                    <div class="form-group">
                                        <label>Nombre</label>
                                        <input type="text" class="form-control" placeholder="Ingrese un nombre">
                                    </div>
                                </div>
                                <div class="col-sm-2">
                                    <div class="form-group">
                                        <label>Estado</label>
                                        <select class="form-control">
                                            <option>Seleccione</option>
                                            <option>Activo</option>
                                            <option>Inactivo</option>
                                        </select>
                                    </div>
                                </div>
                                <div class="col-sm-6 align-self-center">
                                    <div class="btn-group float-right">
                                        <button type="button" class="btn btn-default">
                                            <i class="fas fa-eraser"></i>&nbsp;&nbsp;Limpiar
                                        </button>
                                        <button type="button" class="btn btn-primary">
                                            <i class="fas fa-search"></i>&nbsp;&nbsp;Consultar
                                        </button>
                                    </div>
                                </div>
                            </div>
                        </form>


                    </div>
                    <!-- /.card-body -->
                </div>
                <!-- /.card -->
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->

        <div class="row">
            <div class="col-md-12">
                <div class="card card-outline card-primary">
                    <div class="card-header">
                        <h3 class="card-title">Resultados de la Consulta</h3>
                        <a asp-controller="Opcion" asp-action="Registrar" class="btn btn-info float-right">
                            <i class="fas fa-file"></i>&nbsp;&nbsp;Nuevo
                        </a>
                    </div>
                    <!-- /.card-header -->
                    <div class="card-body">

                        <table id="opcion-datatable" class="table table-hover table-striped">
                            <thead>
                                <tr>
                                    <th>ID</th>
                                    <th>Nombre</th>
                                    <th>Descripcion</th>
                                    <th>Estado</th>
                                    <th>Regist. Por</th>
                                    <th>Fecha</th>
                                    <th></th>
                                </tr>
                            </thead>
                            <!-- Body table -->
                            <tbody>
                                <tr>
                                    <td>1</td>
                                    <td>Inicio</td>
                                    <td>Opción Inicial</td>
                                    <td>Activo</td>
                                    <td>Admin</td>
                                    <td>15/01/2021 15:20:21</td>
                                    <td>
                                        <a asp-controller="Opcion" asp-action="Editar" class="btn btn-block btn-outline-warning btn-sm">
                                            <i class="fas fa-edit"></i>
                                        </a>
                                    </td>
                                </tr>
                                <tr>
                                    <td>2</td>
                                    <td>Administración</td>
                                    <td>Opción Inicial</td>
                                    <td>Activo</td>
                                    <td>Admin</td>
                                    <td>15/01/2021 15:20:21</td>
                                    <td>
                                        <a asp-controller="Opcion" asp-action="Editar" class="btn btn-block btn-outline-warning btn-sm">
                                            <i class="fas fa-edit"></i>
                                        </a>
                                    </td>
                                </tr>
                                <tr>
                                    <td>3</td>
                                    <td>Seguridad</td>
                                    <td>Opción Inicial</td>
                                    <td>Activo</td>
                                    <td>Admin</td>
                                    <td>15/01/2021 15:20:21</td>
                                    <td>
                                        <a asp-controller="Opcion" asp-action="Editar" class="btn btn-block btn-outline-warning btn-sm">
                                            <i class="fas fa-edit"></i>
                                        </a>
                                    </td>
                                </tr>
                                <tr>
                                    <td>4</td>
                                    <td>Opción</td>
                                    <td>Opción Inicial</td>
                                    <td>Activo</td>
                                    <td>Admin</td>
                                    <td>15/01/2021 15:20:21</td>
                                    <td>
                                        <a asp-controller="Opcion" asp-action="Editar" class="btn btn-block btn-outline-warning btn-sm">
                                            <i class="fas fa-edit"></i>
                                        </a>
                                    </td>
                                </tr>
                                <tr>
                                    <td>5</td>
                                    <td>Perfil</td>
                                    <td>Opción Inicial</td>
                                    <td>Activo</td>
                                    <td>Admin</td>
                                    <td>15/01/2021 15:20:21</td>
                                    <td>
                                        <a asp-controller="Opcion" asp-action="Editar" class="btn btn-block btn-outline-warning btn-sm">
                                            <i class="fas fa-edit"></i>
                                        </a>
                                    </td>
                                </tr>
                                <tr>
                                    <td>6</td>
                                    <td>usuario</td>
                                    <td>Opción Inicial</td>
                                    <td>Activo</td>
                                    <td>Admin</td>
                                    <td>15/01/2021 15:20:21</td>
                                    <td>
                                        <a asp-controller="Opcion" asp-action="Editar" class="btn btn-block btn-outline-warning btn-sm">
                                            <i class="fas fa-edit"></i>
                                        </a>
                                    </td>
                                </tr>
                            </tbody>
                            <!-- /Body table -->
                        </table>

                    </div>
                    <!-- /.card-body -->
                </div>
                <!-- /.card -->
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->

    </div><!-- /.container-fluid -->
</section>
<!-- /.content -->

@section Scripts {
    <script type="text/javascript" src="~/dist/js/Seguridad/Opcion/index.js"></script>
}

slnVELogisticCloud/VELogisticCloud.App.Web/Views/Seguridad/Opcion/Registro.cshtml
@{
    Layout = "_Layout";
}
<!-- Content Header (Page header) -->
<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Opci&oacute;n</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a asp-controller="Home" asp-action="Index">Inicio</a></li>
                    <li class="breadcrumb-item">Administraci&oacute;n</li>
                    <li class="breadcrumb-item">Seguridad</li>
                    <li class="breadcrumb-item"><a asp-controller="Opcion" asp-action="Index">Opci&oacute;n</a></li>
                    <li class="breadcrumb-item active">Registrar</li>
                </ol>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>

<!-- Main content -->
<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card card-outline card-primary">
                    <div class="card-header">
                        <h3 class="card-title">Registrar Opci&oacute;n</h3>
                    </div>
                    <!-- /.card-header -->

                    <form role="form">
                        <div class="card-body">
                            <div class="row">
                                <div class="col-sm-2">
                                    <!-- text input -->
                                    <div class="form-group">
                                        <label>Id Opción</label>
                                        <input type="text" class="form-control" disabled>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-sm-4">
                                    <!-- text input -->
                                    <div class="form-group">
                                        <label>Tipo de Opción</label>
                                        <select class="form-control">
                                            <option>Seleccione</option>
                                        </select>
                                    </div>
                                </div>
                                <div class="col-sm-4">
                                    <!-- text input -->
                                    <div class="form-group">
                                        <label>Opción Padre</label>
                                        <select class="form-control">
                                            <option>Seleccione</option>
                                        </select>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-sm-4">
                                    <!-- text input -->
                                    <div class="form-group">
                                        <label>Nombre</label>
                                        <input type="text" class="form-control" placeholder="Nombre de la Opción">
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-sm-8">
                                    <!-- text input -->
                                    <div class="form-group">
                                        <label>Descripción</label>
                                        <input type="text" class="form-control" placeholder="Descripción de la Opción">
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-sm-4">
                                    <!-- text input -->
                                    <div class="form-group">
                                        <label>Controlador</label>
                                        <input type="text" class="form-control" placeholder="Nombre del Controller">
                                    </div>
                                </div>
                                <div class="col-sm-4">
                                    <!-- text input -->
                                    <div class="form-group">
                                        <label>Acción</label>
                                        <input type="text" class="form-control" placeholder="Nombre del Action">
                                    </div>
                                </div>                            
                                <div class="col-sm-2">
                                    <!-- text input -->
                                    <div class="form-group">
                                        <label>Orden</label>
                                        <input type="text" class="form-control" placeholder="Nro.">
                                    </div>
                                </div>
                                <div class="col-sm-2">
                                    <div class="form-group">
                                        <label>Estado</label>
                                        <select class="form-control">
                                            <option>Seleccione</option>
                                            <option>Activo</option>
                                            <option>Inactivo</option>
                                        </select>
                                    </div>
                                </div>
                            </div>

                            <hr>

                            <div class="row">
                                <div class="col-sm-4">
                                    <!-- text input -->
                                    <div class="form-group">
                                        <label>Registrado por</label>
                                        <input type="text" class="form-control" disabled>
                                    </div>
                                </div>
                                <div class="col-sm-4">
                                    <!-- text input -->
                                    <div class="form-group">
                                        <label>Fecha de Registro</label>
                                        <input type="text" class="form-control" disabled>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-sm-4">
                                    <!-- text input -->
                                    <div class="form-group">
                                        <label>Modificado por</label>
                                        <input type="text" class="form-control" disabled>
                                    </div>
                                </div>
                                <div class="col-sm-4">
                                    <!-- text input -->
                                    <div class="form-group">
                                        <label>Fecha de Modificación</label>
                                        <input type="text" class="form-control" disabled>
                                    </div>
                                </div>
                            </div>
                        </div>
                        
                        <!-- /.card-body -->
                        <div class="card-footer">
                            <div class="float-right">
                                <button type="button" class="btn btn-default">
                                    <i class="fas fa-undo"></i>&nbsp;&nbsp;Cancelar
                                </button>
                                <button type="button" class="btn btn-default">
                                    <i class="fas fa-eraser"></i>&nbsp;&nbsp;Limpiar
                                </button>
                                <button type="button" class="btn btn-primary">
                                    <i class="fas fa-save"></i>&nbsp;&nbsp;Registrar
                                </button>
                            </div>                           
                        </div>
                    </form>
                </div>
                <!-- /.card -->
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
        
    </div><!-- /.container-fluid -->
</section>
<!-- /.content -->