slnVELogisticCloud/VELogisticCloud.App.Web/Models/Seguridad/PerfilViewModel.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace VELogisticCloud.App.Web.Models.Seguridad
{
    public class PerfilViewModel
    {
        [Key]
        public int IdPerfil { get; set; }

        [Required(ErrorMessage = "El campo {0} es obligatorio.")]
        public string Nombre { get; set; }

        [Required(ErrorMessage = "El campo {0} es obligatorio.")]
        public string Descripcion { get; set; }

        public int IdEstado { get; set; }

        public int IdUsuarioRegistro { get; set; }

        public DateTime FechaRegistro { get; set; }

        public int IdUsuarioActualiza { get; set; }

        public string FechaActualizacion { get; set; }
    }
}

slnVELogisticCloud/VELogisticCloud.App.Web/Models/Seguridad/UsuarioRegistroViewModel.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
//using VELogisticCloud.CrossCutting.Entidad.Seguridad;

namespace VELogisticCloud.App.Web.Models.Seguridad
{
    public class UsuarioRegistroViewModel
    {
        [Required]        
        [Display(Name = "Login")]
        public string Login { get; set; }

        [Required]
        [EmailAddress]
        [Display(Name = "Email")]
        public string Email { get; set; }

        [Required]
        [StringLength(20, ErrorMessage = "El {0} debe tener al menos {2} y un maximo de {1} characters.", MinimumLength = 6)]
        [DataType(DataType.Password)]
        [Display(Name = "Password")]
        public string Password { get; set; }

        [DataType(DataType.Password)]
        [Display(Name = "Confirmar password")]
        [Compare("Password", ErrorMessage = "El password y la confirmacion del password no coinciden.")]
        public string ConfirmPassword { get; set; }

        [Required(ErrorMessage = "El campo {0} es obligatorio.")]
        public string Apellidos { get; set; }

        [Required(ErrorMessage = "El campo {0} es obligatorio.")]
        public string Nombres { get; set; }

        public string TelefonoMovil { get; set; }

        [Required(ErrorMessage = "Seleccione un Estado valido.")]        
        public int IdEstado { get; set; }

        //public List<Estado> Estados { get; set; }

        public string FechaRegistro { get; set; }
    }
}

slnVELogisticCloud/VELogisticCloud.App.Web/Models/Seguridad/UsuarioViewModel.cs
using System.Collections.Generic;
//using VELogisticCloud.CrossCutting.Entidad.Seguridad;

namespace VELogisticCloud.App.Web.Models.Seguridad
{
    public class UsuarioViewModel
    {
        //public Usuario Entidad { get; set; }
        //public List<Estado> Estados { get; set; }
    }
}

slnVELogisticCloud/VELogisticCloud.App.Web/Controllers/Seguridad/OpcionController.cs
using Microsoft.AspNetCore.Mvc;

namespace VELogisticCloud.App.Web.Controllers.Seguridad
{
    public class OpcionController : Controller
    {
        [HttpGet]
        public IActionResult Index()
        {
            return View("~/Views/Seguridad/Opcion/Index.cshtml");
        }

        [HttpGet]
        public IActionResult Registrar()
        {
            return View("~/Views/Seguridad/Opcion/Registro.cshtml");
        }

        [HttpGet]
        public IActionResult Editar()
        {
            return View("~/Views/Seguridad/Opcion/Registro.cshtml");
        }

    }
}

slnVELogisticCloud/VELogisticCloud.App.Web/Controllers/Seguridad/PerfilController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using VELogisticCloud.Models;
using VELogisticCloud.Servicio.Data.Repository;

namespace VELogisticCloud.App.Web.Controllers.Seguridad
{
    public class PerfilController : Controller
    {
        private readonly IContenedorTrabajo _contenedorTrabajo;

        public PerfilController(IContenedorTrabajo contenedorTrabajo)
        {
            _contenedorTrabajo = contenedorTrabajo;
        }

        public IActionResult Index()
        {
            return View("~/Views/Seguridad/Perfil/Index.cshtml");
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View("~/Views/Seguridad/Perfil/Create.cshtml");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Perfil entidad)
        {
            if (ModelState.IsValid)
            {
                entidad.IdUsuarioRegistro = 1;
                entidad.FechaRegistro = DateTime.Now;

                //entidad.IdUsuarioActualiza = 1;
                //entidad.FechaActualizacion = DateTime.Now;

                _contenedorTrabajo.Perfil.Add(entidad);
                _contenedorTrabajo.Save();
                return RedirectToAction(nameof(Index));
            }
            return View("~/Views/Seguridad/Perfil/Create.cshtml",entidad);
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            Perfil entidad = _contenedorTrabajo.Perfil.Get(id);
            if (entidad == null)
            {
                return NotFound();
            }

            return View("~/Views/Seguridad/Perfil/Edit.cshtml",entidad);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Perfil entidad)
        {
            if (ModelState.IsValid)
            {
                _contenedorTrabajo.Perfil.Update(entidad);
                _contenedorTrabajo.Save();
                return RedirectToAction(nameof(Index));
            }
            return View("~/Views/Seguridad/Perfil/Edit.cshtml",entidad);
        }


        #region llamadas API

        [HttpGet]
        public IActionResult GetAll()
        {
            return Json(new { data = _contenedorTrabajo.Perfil.GetAll() });
        }

        [HttpDelete]
        public IActionResult Delete(int id)
        {
            var objFromDb = _contenedorTrabajo.Perfil.Get(id);
            if (objFromDb == null)
            {
                return Json(new { success = false, message = "Error eliminando perfil" });
            }

            _contenedorTrabajo.Perfil.Remove(objFromDb);
            _contenedorTrabajo.Save();
            return Json(new { success = true, message = "Puerto borrado satisfactoriamente." });
        }

        #endregion
    }
}

slnVELogisticCloud/VELogisticCloud.App.Web/Controllers/Seguridad/RolController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using VELogisticCloud.Models.Security;

namespace VELogisticCloud.App.Web.Controllers.Seguridad
{
    public class RolController : Controller
    {
        private readonly RoleManager<IdentityRole> _roleManager;

        public RolController(RoleManager<IdentityRole> roleManager)
        {
            _roleManager = roleManager;
        }

        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View("~/Views/Seguridad/Perfil/Create.cshtml");
        }

        [HttpPost]
        public async Task<IActionResult> Create(RolViewModel model)
        {

            IdentityRole identityRole = new IdentityRole()
            {
                Name = model.Nombre
            };

            var result = await _roleManager.CreateAsync(identityRole);

            return View("~/Views/Seguridad/Perfil/Create.cshtml", model);
        }
    }
}

slnVELogisticCloud/VELogisticCloud.App.Web/Controllers/Seguridad/UsuarioController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using VELogisticCloud.CrossCutting.Comun;
using VELogisticCloud.CrossCutting.DTO;
using VELogisticCloud.Model.Identity;
using VELogisticCloud.Models.ViewModel;
using VELogisticCloud.Servicio.Data;
using VELogisticCloud.Servicio.Data.Repository;

namespace VELogisticCloud.App.Web.Controllers.Seguridad
{
    [Authorize(Roles = Rol.ADMINISTRADOR)]
    public class UsuarioController : Controller
    {
        private readonly IContenedorTrabajo _contenedorTrabajo;

        public UsuarioController(IContenedorTrabajo contenedorTrabajo)
        {
            _contenedorTrabajo = contenedorTrabajo;
        }

        [HttpGet]
        public IActionResult Index()
        {
            UsuarioViewModel model = new UsuarioViewModel();

            model.Estados = new EstadoRepository().GetListaEstado().ToList();

            return View("~/Views/Seguridad/Usuario/Index.cshtml", model);
        }

        [HttpPost]
        //[Authorize]
        public async Task<IActionResult> ListarUsuario(UsuarioDTO usuario)
        {

            EntidadConsultada<UsuarioDTO> response = new EntidadConsultada<UsuarioDTO>();

            var draw = HttpContext.Request.Form["draw"].FirstOrDefault();
            var start = Request.Form["start"].FirstOrDefault();
            var length = Request.Form["length"].FirstOrDefault();

            response = await _contenedorTrabajo.Usuario.ListarUsuarios(usuario,
                                                        start != null ? Convert.ToInt32(start) : 0,
                                                        length != null ? Convert.ToInt32(length) : 0);
            response.Lista.ForEach(a => a.NombreEstado = "Activo");

            //foreach (var item in response.Lista)
            //{
            //    if (item.Email == "admin@mail.com")
            //        item.NombreRol = "Administrador";
            //    else if (item.Email == "customer@mail.com")
            //        item.NombreRol = "Customer Service";
            //    else
            //        item.NombreRol = "Usuario";
            //}

            return Json(new
            {
                draw,
                recordsFiltered = response.Lista.Count(),
                recordsTotal = response.TotalRegistros,
                data = response.Lista
            });
        }
    }
}

slnVELogisticCloud/VELogisticCloud.App.Web/Views/Seguridad/Perfil/Create.cshtml
@model VELogisticCloud.Models.Security.RolViewModel
@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<br />
<br />
<h3 class="text-center">Crear una nueva categoría</h3>
<form method="post" asp-action="Create">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="col-10 offset-1 mt-4">
        <div class="form-group row">
            <div class="col-4">
                <label asp-for="Nombre"></label>
            </div>
            <div class="col-8">
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group row">
            <div class="col-8 offset-4">
                <partial name="_VistaCrearVolver" />
            </div>
        </div>
    </div>
</form>

slnVELogisticCloud/VELogisticCloud.App.Web/Views/Seguridad/Perfil/Edit.cshtml
@model VELogisticCloud.Models.Perfil
@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<br />
<br />
<h3 class="text-center">Crear una nueva categoría</h3>
<form method="post" asp-action="Edit">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <input type="hidden" asp-for="IdPerfil" />
    <div class="col-10 offset-1 mt-4">
        <div class="form-group row">
            <div class="col-4">
                <label asp-for="Nombre"></label>
            </div>
            <div class="col-8">
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group row">
            <div class="col-4">
                <label asp-for="Descripcion"></label>
            </div>
            <div class="col-8">
                <input asp-for="Descripcion" class="form-control" />
                <span asp-validation-for="Descripcion" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group row">
            <div class="col-4">
                <label asp-for="IdEstado"></label>
            </div>
            <div class="col-8">
                <input asp-for="IdEstado" class="form-control" />
                <span asp-validation-for="IdEstado" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group row">
            <div class="col-8 offset-4">
                <div class="row">
                    <div class="col">
                        <button type="submit" class="btn btn-primary form-control" asp-route-id="@Model.IdPerfil">Actualizar</button>
                        &nbsp;
                    </div>
                    <div class="col">
                        <a asp-action="Index" class="btn btn-success form-control">Volver a lista</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>

slnVELogisticCloud/VELogisticCloud.App.Web/Views/Seguridad/Perfil/Index.cshtml
@{
    Layout = "_Layout";
}
<!-- Content Header (Page header) -->
<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Perfil</h1>
            </div>            
        </div>
    </div><!-- /.container-fluid -->
</section>


<!-- Main content -->
<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card card-outline card-primary">
                    <div class="card-header">
                        <h3 class="card-title">Filtros de Consulta</h3>
                        <div class="card-tools">
                            <button type="button" class="btn btn-tool" data-card-widget="collapse">
                                <i class="fas fa-minus"></i>
                            </button>
                        </div>
                        <!-- /.card-tools -->
                    </div>
                    <!-- /.card-header -->
                    <div class="card-body">

                        <form role="form">
                            <div class="row">
                                <div class="col-sm-4">
                                    <!-- text input -->
                                    <div class="form-group">
                                        <label>Nombre</label>
                                        <input type="text" class="form-control" placeholder="Ingrese un nombre">
                                    </div>
                                </div>
                                <div class="col-sm-2">
                                    <div class="form-group">
                                        <label>Estado</label>
                                        <select class="form-control">
                                            <option>Seleccione</option>
                                            <option>Activo</option>
                                            <option>Inactivo</option>
                                        </select>
                                    </div>
                                </div>
                                <div class="col-sm-6 align-self-center">
                                    <div class="btn-group float-right">
                                        <button type="button" class="btn btn-default">
                                            <i class="fas fa-eraser"></i>&nbsp;&nbsp;Limpiar
                                        </button>
                                        <button type="button" class="btn btn-primary">
                                            <i class="fas fa-search"></i>&nbsp;&nbsp;Consultar
                                        </button>
                                    </div>
                                </div>
                            </div>
                        </form>


                    </div>
                    <!-- /.card-body -->
                </div>
                <!-- /.card -->
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->

        <div class="row">
            <div class="col-md-12">
                <div class="card card-outline card-primary">
                    <div class="card-header">
                        <h3 class="card-title">Resultados de la Consulta</h3>
                        <a asp-controller="Perfil" asp-action="Create" class="btn btn-info float-right">
                            <i class="fas fa-plus"></i>&nbsp;&nbsp;Nuevo
                        </a>
                    </div>
                    <!-- /.card-header -->
                    <div class="card-body">

                        <table id="tblPerfil" class="table table-hover table-striped">
                            <thead>
                                <tr>
                                    <th>Nombre</th>
                                    <th>Descripcion</th>
                                    <th>Estado</th>
                                    <th></th>
                                </tr>
                            </thead>
                        </table>

                    </div>
                    <!-- /.card-body -->
                </div>
                <!-- /.card -->
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->

    </div><!-- /.container-fluid -->
</section>
<!-- /.content -->

@section Scripts {
    <script type="text/javascript" src="~/dist/js/Seguridad/perfil.js"></script>
}

slnVELogisticCloud/VELogisticCloud.App.Web/Views/Seguridad/Perfil/Registro.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}