slnVELogisticCloud/VELogisticCloud.App.Web/Controllers/Admin/PuertoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using VELogisticCloud.Models;
using VELogisticCloud.Servicio.Data.Repository;

namespace VELogisticCloud.App.Web.Controllers.Admin
{
    public class PuertoController : Controller
    {
        private readonly IContenedorTrabajo _contenedorTrabajo;
        public PuertoController(IContenedorTrabajo contenedorTrabajo)
        {
            _contenedorTrabajo = contenedorTrabajo;
        }

        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Puerto entidad)
        {
            if (ModelState.IsValid)
            {
                _contenedorTrabajo.Puerto.Add(entidad);
                _contenedorTrabajo.Save();
                return RedirectToAction(nameof(Index));
            }
            return View(entidad);
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            Puerto puerto = _contenedorTrabajo.Puerto.Get(id);
            if (puerto == null)
            {
                return NotFound();
            }

            return View(puerto);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Puerto entidad)
        {
            if (ModelState.IsValid)
            {
                _contenedorTrabajo.Puerto.Update(entidad);
                _contenedorTrabajo.Save();
                return RedirectToAction(nameof(Index));
            }
            return View(entidad);
        }



        #region llamadas API

        [HttpGet]
        public IActionResult GetAll()
        {
            return Json(new { data = _contenedorTrabajo.Puerto.GetAll() });
        }

        [HttpDelete]
        public IActionResult Delete(int id)
        {
            var objFromDb = _contenedorTrabajo.Puerto.Get(id);
            if (objFromDb == null)
            {
                return Json(new { success = false, message = "Error eliminando puerto" });
            }

            _contenedorTrabajo.Puerto.Remove(objFromDb);
            _contenedorTrabajo.Save();
            return Json(new { success = true, message = "Puerto borrado satisfactoriamente." });
        }

        #endregion
    }
}

slnVELogisticCloud/VELogisticCloud.App.Web/Views/Puerto/Create.cshtml
@model VELogisticCloud.Models.Puerto
@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<br />
<br />
<h3 class="text-center">Crear un nuevo Puerto</h3>
<form method="post" asp-action="Create">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="col-10 offset-1 mt-4">
        <div class="form-group row">
            <div class="col-4">
                <label asp-for="Codigo"></label>
            </div>
            <div class="col-8">
                <input asp-for="Codigo" class="form-control" />
                <span asp-validation-for="Codigo" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group row">
            <div class="col-4">
                <label asp-for="Nombre"></label>
            </div>
            <div class="col-8">
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group row">
            <div class="col-4">
                <label asp-for="Descripcion"></label>
            </div>
            <div class="col-8">
                <input asp-for="Descripcion" class="form-control" />
                <span asp-validation-for="Descripcion" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group row">
            <div class="col-8 offset-4">
                <partial name="_VistaCrearVolver" />
            </div>
        </div>
    </div>
</form>

slnVELogisticCloud/VELogisticCloud.App.Web/Views/Puerto/Edit.cshtml
@model  VELogisticCloud.Models.Puerto
@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<br />
<br />
<h3 class="text-center">Crear un nuevo Puerto</h3>
<form method="post" asp-action="Edit">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <input type="hidden" asp-for="IdPuerto" />
    <div class="col-10 offset-1 mt-4">
        <div class="form-group row">
            <div class="col-4">
                <label asp-for="Codigo"></label>
            </div>
            <div class="col-8">
                <input asp-for="Codigo" class="form-control" />
                <span asp-validation-for="Codigo" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group row">
            <div class="col-4">
                <label asp-for="Nombre"></label>
            </div>
            <div class="col-8">
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group row">
            <div class="col-4">
                <label asp-for="Descripcion"></label>
            </div>
            <div class="col-8">
                <input asp-for="Descripcion" class="form-control" />
                <span asp-validation-for="Descripcion" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group row">
            <div class="col-8 offset-4">
                <div class="row">
                    <div class="col">
                        <button type="submit" class="btn btn-primary form-control" asp-route-id="@Model.IdPuerto">Actualizar</button>
                        &nbsp;
                    </div>
                    <div class="col">
                        <a asp-action="Index" class="btn btn-success form-control">Volver a lista</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>

slnVELogisticCloud/VELogisticCloud.App.Web/Views/Puerto/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<!-- Main content -->
<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card card-outline card-primary">
                    <div class="card-header">
                        <h3 class="card-title">Filtros de Consulta</h3>
                        <div class="card-tools">
                            <button type="button" class="btn btn-tool" data-card-widget="collapse">
                                <i class="fas fa-minus"></i>
                            </button>
                        </div>
                        <!-- /.card-tools -->
                    </div>
                    <!-- /.card-header -->
                    <div class="card-body">

                        <form role="form">
                            <div class="row">
                                <div class="col-sm-4">
                                    <!-- text input -->
                                    <div class="form-group">
                                        <label>Nombre</label>
                                        <input type="text" class="form-control" placeholder="Ingrese un nombre">
                                    </div>
                                </div>
                                <div class="col-sm-2">
                                    <div class="form-group">
                                        <label>Estado</label>
                                        <select class="form-control">
                                            <option>Seleccione</option>
                                            <option>Activo</option>
                                            <option>Inactivo</option>
                                        </select>
                                    </div>
                                </div>
                                <div class="col-sm-6 align-self-center">
                                    <div class="btn-group float-right">
                                        <button type="button" class="btn btn-default">
                                            <i class="fas fa-eraser"></i>&nbsp;&nbsp;Limpiar
                                        </button>
                                        <button type="button" class="btn btn-primary">
                                            <i class="fas fa-search"></i>&nbsp;&nbsp;Consultar
                                        </button>
                                    </div>
                                </div>
                            </div>
                        </form>


                    </div>
                    <!-- /.card-body -->
                </div>
                <!-- /.card -->
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->

        <div class="row">
            <div class="col-md-12">
                <div class="card card-outline card-primary">
                    <div class="card-header">
                        <h3 class="card-title">Resultados de la Consulta</h3>
                        <a asp-controller="Puerto" asp-action="Create" class="btn btn-info float-right">
                            <i class="fas fa-plus"></i>&nbsp;&nbsp;Nuevo
                        </a>
                    </div>
                    <!-- /.card-header -->
                    <div class="card-body">
                        <table id="tblPuerto" class="table table-hover table-striped">
                            <thead>
                                <tr>
                                    <th>Codigo</th>
                                    <th>Nombre</th>
                                    <th>Descripcion</th>
                                    <th></th>
                                </tr>
                            </thead>
                        </table>
                    </div>
                    <!-- /.card-body -->
                </div>
                <!-- /.card -->
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->

    </div><!-- /.container-fluid -->
</section>
<!-- /.content -->

@section Scripts {
    <script type="text/javascript" src="~/dist/js/Admin/puerto.js"></script>
}